### ISSUE TITLE
monit binary not in `PATH` when installed using binaries

### ISSUE THREAD

**Issue by gretel** [poise/poise-monit#11]
looking at the code i see

```
# (see Base#monit_binary)
def monit_binary
  ::File.join(static_folder, 'bin', 'monit')
end
```

but i'm unsure how i'd add it to the `PATH` so the `monit` binary would be callable without knowing which version is installed.

**Comment by coderanger** [comment]
Lots of ways you could do it in bash, mostly depending on how you want to handle multiple versions, but off the top of my head:

``` bash
export PATH="$(ls /opt/monit* | head -n 1 | tr -d "\n")/bin:$PATH"
```

**Comment by coderanger** [comment]
Another option would be to have Chef generate a snippet of shell script to include in interactive shells (most linuxes have something like `/etc/profile.d`) with the path to the monit you want.

**Comment by gretel** [comment]
sure, thanks, but my concern is having multiple versions installed (by accident/failure). i do have a cookbook setting `PATH` fine, but i am unaware of the version number that `poise-monit` did install.
could a node attribute be set containing the version number of monit installed? using this value lazily in the the recipe setting `PATH` would be great. regards

**Comment by coderanger** [comment]
It isn't available as an attribute, but you can get it directly from the monit resource:

``` ruby
file '/etc/profile.d/monit.sh' do
  content lazy { "export PATH=#{::File.dirname(resources('monit[monit]').monit_binary)}:$PATH" }
end
```

Make sure to adjust to match the name of your monit resource if it isn't the default one.

**Comment by coderanger** [comment]
That will also work for any provider, it's part of the internal API of the monit resource.

**Comment by gretel** [comment]
ok, that works, thanks. but now i got an issues with the configuration file being at a location `monit` won't find easily:

```
$ which monit
/opt/monit-5.16/bin/monit
$ monit summary
Cannot find the control file at ~/.monitrc, /etc/monitrc, /usr/local/etc/monitrc, /usr/local/etc/monitrc or at ./monitrc
```

i wonder if that is correct since the `monit` resource is declared including

```
  path '/etc/monit'
```

**Comment by coderanger** [comment]
You can get that from the resource too, `resources('monit[monit]').config_path`.

**Comment by gretel** [comment]
i did ditch `/etc/monit` and removed it from the declaration, too. seems to work fine now:

```
monit_path = ::File.dirname(resources('monit[monit]').monit_binary)

file '/etc/profile.d/monit.sh' do
  content <<-EOH
export PATH=#{monit_path}:$PATH
ln -sf /etc/monit/monitrc /etc/monitrc
EOH
end
```

regards

**Comment by coderanger** [comment]
Probably a terrible idea to create the symlink in a shell init file like that. It's a bad idea in general, but that's a really bad idea. ¯_(ツ)_/¯

**Comment by gretel** [comment]
i'm very open to less-messy solutions, but for now i do require something working.

**Comment by coderanger** [comment]
The less messy solution is to store the config path in an environment variable or something and use `-c` like all the internal code does.

Another option is to write out a wrapper like this:

``` ruby
file '/usr/local/bin/monit' do
  mode '755'
  content lazy { <<-EOH }
#!/bin/sh
#{resources('monit[monit]').monit_binary} -c #{resources('monit[monit]').config_path} $@
EOH
end
```

Or something like that, double check the `$@` as my bash is a little rusty.

**Comment by coderanger** [comment]
Or alternatively, don't expect Chef to create stuff that interacts super well with working by hand. The needs of automation and the needs of humans are at best unrelated.

**Comment by gretel** [comment]
@coderanger uh, looks lazily awesome. thanks a million. alternatively - well, monit needs to be accessible via ssh - it's kinda intrinsic for it's concept, i'd say. truly automated systems would not be available via ssh or similar. muchos regardos!

**Comment by coderanger** [comment]
Closing this out as several workarounds were provided.
