### ISSUE TITLE
How to use latest master directly from github

### ISSUE THREAD

**Issue by nazarhussain** [poise/poise-monit#17]
Hello,

I want to make some changes and I did a fork of this repo. But while using a direct repo url or path in `Berksfile` it shows following error. 

```
ridley-4.5.1/lib/ridley/chef/cookbook.rb:40:in `from_path': no metadata.json or metadata.rb found at diretory/path/poise-monit (IOError)
```

Any one knows what could be reason?

**Comment by coderanger** [comment]
There are instructions in the Halite readme but there are no commits not in the latest release that would matter so there is no reason to do this.
