### ISSUE TITLE
Monitor `runit` service

### ISSUE THREAD

**Issue by imewish** [poise/poise-monit#20]
Hi , 

I have logstash installed on my machine and its service is managed by `runit` (/usr/bin/sv start logstash_server),

How do i monitor this , with monit_check resource?

i have tried like this , but didnt work,

```
monit_check 'logstash' do

    check_type "process"
    start_program "/usr/bin/sv start logstash_server"
    stop_program  "/usr/bin/sv stop logstash_server"
    extra [
    "alert #{node[:monit][:alert_email]} only on {nonexist}"
  ]

end

```

helps would be appreciated.

**Comment by coderanger** [comment]
You would want to put monit in to passive mode because runit (like most process managers) already handles restarting the service if it crashes.

**Comment by imewish** [comment]
Im a beginner to monit, can you help me to understand how to put monit into "passive mode"?

**Comment by coderanger** [comment]
No, sorry, this cookbook is not a replacement for the monit manual. If you're not familiar with Monit already, I probably wouldn't use it. Runit on its own (or Upstart or systemd if you want something built in) is much simpler and already handles the most important bit of making sure the service stays running.

**Comment by imewish** [comment]
Okay, Thanks.
