### ISSUE TITLE
Installing package leads to poise/backports/verify_path problem

### ISSUE THREAD

**Issue by jjustice6** [poise/poise-monit#24]
```[2016-12-15T12:40:49-05:00] INFO: Processing yum_package[tar] action install (/var/chef/cache/cookbooks/poise-archive/files/halite_gem/poise_archive/archive_providers/gnu_tar.rb line 57)

================================================================================
Error executing action `enable` on resource 'monit[monit]'
================================================================================

LoadError
---------
cannot load such file -- poise/backports/verify_path

Cookbook Trace:
---------------
/var/chef/cache/cookbooks/poise-monit/files/halite_gem/poise_monit/monit_providers/base.rb:144:in `block in write_config'
/var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/resource_builder.rb:90:in `instance_eval'
/var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/resource_builder.rb:90:in `build'
/var/chef/cache/cookbooks/poise-monit/files/halite_gem/poise_monit/monit_providers/base.rb:138:in `write_config'
/var/chef/cache/cookbooks/poise-monit/files/halite_gem/poise_monit/monit_providers/base.rb:48:in `block in action_enable'
/var/chef/cache/cookbooks/poise/files/halite_gem/poise/helpers/subcontext_block.rb:54:in `instance_eval'
/var/chef/cache/cookbooks/poise/files/halite_gem/poise/helpers/subcontext_block.rb:54:in `subcontext_block'
/var/chef/cache/cookbooks/poise/files/halite_gem/poise/helpers/notifying_block.rb:67:in `notifying_block'
/var/chef/cache/cookbooks/poise-monit/files/halite_gem/poise_monit/monit_providers/base.rb:41:in `action_enable'
/var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:78:in `run_action'
/var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `block (2 levels) in converge'
/var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `each'
/var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `block in converge'
/var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:105:in `converge'

Resource Declaration:
---------------------


Compiled Resource:
------------------
# Declared in /var/chef/cache/cookbooks/(our cookbook):in `from_file'

monit("monit") do
  provider PoiseMonit::MonitProviders::Binaries
  action [:enable]
  updated true
  retries 0
  retry_delay 2
  default_guard_interpreter :default
  subresources [monit_config[enable_monit_httpd]]
  declared_type :monit
  cookbook_name "(omitted)"
  recipe_name "(omitted)"
  owner "monit"
  group "monit"
  logfile "/var/log/monit/monit.log"
  pidfile "/opt/inf/var/run/monit/monit.pid"
  daemon_interval 15
  version "5.17.1"
  options_binaries {"url"=>"http://(internal mirror)/monit/%{version}/monit-%{version}-%{machine_label}.tar.gz"}
  service_name "monit"
  path "/etc/monit"
  var_path "/var/lib/monit"
  monit_version #<Gem::Version "5.17.1">
  httpd_port "/var/run/monit.sock"
  config_content "# Generated by Chef for monit[monit]\n\n\nSET PIDFILE /opt/inf/var/run/monit/monit.pid\n\nSET LOGFILE /var/log/monit/monit.log\n\nSET IDFILE /var/lib/monit/id\nSET STATEFILE /var/lib/monit/state\nSET EVENTQUEUE BASEDIR /var/lib/monit/events SLOTS 100\n\nSET HTTPD UNIXSOCKET /var/run/monit.sock\n  ALLOW 0.0.0.0/0\n\nINCLUDE /etc/monit/conf.d/*\n"
  config_cookbook "poise-monit"
  event_slots 100
end

Platform:
---------
x86_64-linux

```

**Comment by coderanger** [comment]
Check the version of `poise` up at the top of the run?

**Comment by jjustice6** [comment]
- poise (2.7.1)
  - poise-monit (1.6.0)

**Comment by coderanger** [comment]
Sounds like maybe something interfering with the halite gem loading code? Check that the file does appear in the node's cache?

**Comment by jjustice6** [comment]
So, it works on subsequent runs, which makes this (and another, probably unrelated, bug) fiendishly difficult to track down.

I just stood up a brand-new machine after having this reported to me and can confirm it happens on a first Chef run.

[root@bustedmachine ~]# ls /var/chef/cache/cookbooks/poise/files/halite_gem/poise/
backports  helpers  subcontext  utils
[root@bustedmachine ~]# ls /var/chef/cache/cookbooks/poise/files/halite_gem/poise/backports/
[root@bustedmachine ~]# 

Whereas on a machine that is working:

[root@workingmachine ~]# ls /var/chef/cache/cookbooks/poise/files/halite_gem/poise/
backports     error.rb  helpers.rb   resource.rb  subcontext.rb  utils.rb
backports.rb  helpers   provider.rb  subcontext   utils          version.rb
[root@workingmachine ~] # ls /var/chef/cache/cookbooks/poise/files/halite_gem/poise/backports/
not_passed.rb  verify_path.rb

So there's definitely *something* wrong here.

**Comment by coderanger** [comment]
Which version of Chef and is `no_lazy_load` set to something in the config?

**Comment by jjustice6** [comment]
Chef: 12.16.42

There is no setting for "no_lazy_load" in the config.

We have recently upgraded Chef so it's possible that has something to do with it.

**Comment by coderanger** [comment]
I would turn up the debugging and watch the initial file sync process.

**Comment by jjustice6** [comment]
```
[2016-12-15T15:51:38-05:00] INFO: Storing updated cookbooks/poise/files/halite_gem/poise/backports/verify_path.rb in the cache.
[2016-12-15T15:51:38-05:00] DEBUG: Chef::HTTP calling Chef::HTTP::JSONInput#handle_request
[2016-12-15T15:51:38-05:00] DEBUG: Chef::HTTP calling Chef::HTTP::JSONOutput#handle_request
[2016-12-15T15:51:38-05:00] DEBUG: Chef::HTTP calling Chef::HTTP::CookieManager#handle_request
[2016-12-15T15:51:38-05:00] DEBUG: Chef::HTTP calling Chef::HTTP::Decompressor#handle_request
[2016-12-15T15:51:38-05:00] DEBUG: Chef::HTTP calling Chef::HTTP::Authenticator#handle_request
```

So, it definitely grabs verify_path.rb at some point.

Unfortunately the very next instance of "verify_path" even with that level of debug logging is the "not found" error.

"backports" isn't particularly helpful either:

```
[2016-12-15T15:51:38-05:00] INFO: Storing updated cookbooks/poise/files/halite_gem/poise/backports.rb in the cache.

[2016-12-15T15:51:38-05:00] INFO: Storing updated cookbooks/poise/files/halite_gem/poise/backports/not_passed.rb in the cache.

[2016-12-15T15:51:38-05:00] DEBUG: Creating directory /var/chef/cache/cookbooks/poise/files/halite_gem/poise/backports

[2016-12-15T15:51:38-05:00] INFO: Storing updated cookbooks/poise/files/halite_gem/poise/backports/verify_path.rb in the cache.

cannot load such file -- poise/backports/verify_path
```

I'm at a bit of a loss here.

**Comment by coderanger** [comment]
Just because it is worth ruling out, any chance there is something like a virus scanner or file checker removing the file afterwards?

**Comment by jjustice6** [comment]
Yeah, that's not happening. I also checked for whether the file was getting deleted by our own cookbooks too.

Basically, both this and #25 were tested by spinning up a brand new openstack instance from our standard base image, installing chef, and converging it on a policy.

**Comment by coderanger** [comment]
Next thing to do would be to strace the Chef process (make sure to follow forks) and then look for all syscalls touching that path.

**Comment by rmcleod8** [comment]
So circling back here a year later, this issue IS_NOT cookbook related, we had a condition where an initial bootstrap of a machine was running chef-client without a lockfile. Part of the chef-client run will install a cronjob for chef-client to run with a lockfile. The issue above is a result of a second chef-client run (via cron) before the actual first chef-client run is finished. The second run sees that the node has no run list on the organization so it clears the cookbook cache that the first run was using.

**Comment by coderanger** [comment]
@rmcleod8 That would match the behavior :) Going to close this out.
