### ISSUE TITLE
using a custom startup script

### ISSUE THREAD

**Issue by congaframe** [poise/poise-monit#27]
Hi
I'd like to use different startup script for `/etc/init.d/monit` with this cookbook. I used `template` but it didn't work :
```
monit 'monit' do
  daemon_interval 10
  daemon_delay 2
  event_slots 1000
  httpd_port 3737
  provider :system
  httpd_password "monit"
  httpd_username "monit"
  template "monit_init"
end
```

any ideas ?

**Comment by coderanger** [comment]
The easiest way is to use the `poise_service_options` pseudo-resource:

```ruby
poise_service_options 'monit' do
  provider :sysvinit
  template 'monit_init'
end
```

That said, I don't recommend the use of sysvinit mode, modern OSes have newer systems like Upstart and systemd which will be used automatically normally.

**Comment by congaframe** [comment]
thanks @coderanger . I hit an error  : cookbook `poise-service` not found
I have checked my Berkfile, it is there and I have downloaded that cookbook to my local machine. 
I added both: 
```
depends 'poise-monit'
depends 'poise-service'
```
to my wrapper cookbook

This works fine 
```
poise_service 'myapp' do
  provider :dummy
  command 'myapp --serve'
end
```

**Comment by congaframe** [comment]
ok I found it. 
The problem is this line : `  template 'monit_init'` missing the cookbook. 
So the error line was refering to  ` ` cookbook 
I fixed it by specficy: `  template 'my_cookbook:monit_init'`
