### ISSUE TITLE
poise-monit fails

### ISSUE THREAD

**Issue by ericwingate** [poise/poise-monit#29]
Fails with the following running on the following:

System Info:
------------
chef_version=14.3.37
platform=centos
platform_version=7.4.1708
ruby=ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux]
program_name=/bin/chef-client
executable=/opt/chef/bin/chef-client

================================================================================
Recipe Compile Error in /var/chef/cache/cookbooks/poise-monit/libraries/default.rb
================================================================================

FrozenError
-----------
can't modify frozen Array

Cookbook Trace:
---------------
  /var/chef/cache/cookbooks/poise/files/halite_gem/poise/helpers/subresources/container.rb:220:in `included'
  /var/chef/cache/cookbooks/poise/files/halite_gem/poise/resource.rb:51:in `include'
  /var/chef/cache/cookbooks/poise/files/halite_gem/poise/resource.rb:51:in `poise_subresource_container'
  /var/chef/cache/cookbooks/poise/files/halite_gem/poise.rb:93:in `block in Poise'
  /var/chef/cache/cookbooks/poise-monit/files/halite_gem/poise_monit/resources/monit.rb:44:in `include'
  /var/chef/cache/cookbooks/poise-monit/files/halite_gem/poise_monit/resources/monit.rb:44:in `<class:Resource>'
  /var/chef/cache/cookbooks/poise-monit/files/halite_gem/poise_monit/resources/monit.rb:43:in `<module:Monit>'
  /var/chef/cache/cookbooks/poise-monit/files/halite_gem/poise_monit/resources/monit.rb:29:in `<module:Resources>'
  /var/chef/cache/cookbooks/poise-monit/files/halite_gem/poise_monit/resources/monit.rb:26:in `<module:PoiseMonit>'
  /var/chef/cache/cookbooks/poise-monit/files/halite_gem/poise_monit/resources/monit.rb:25:in `<top (required)>'
  /var/chef/cache/cookbooks/poise-monit/files/halite_gem/poise_monit/resources.rb:17:in `<top (required)>'
  /var/chef/cache/cookbooks/poise-monit/files/halite_gem/poise_monit/cheftie.rb:17:in `<top (required)>'
  /var/chef/cache/cookbooks/poise-monit/libraries/default.rb:19:in `<top (required)>'

Relevant File Content:
----------------------
/var/chef/cache/cookbooks/poise/files/halite_gem/poise/helpers/subresources/container.rb:

213:                @container_default
214:              end
215:            end
216:  
217:            def included(klass)
218:              super
219:              klass.extend(ClassMethods)
220>>             klass.const_get(:HIDDEN_IVARS) << :@subcontexts
221:              klass.const_get(:FORBIDDEN_IVARS) << :@subcontexts
222:            end
223:          end
224:  
225:          extend ClassMethods
226:        end
227:      end
228:    end
229:  end

**Comment by coderanger** [comment]
Upgrade Poise. Also please do better when searching for existing issues. This has been opening dozens of times by now.
