### ISSUE TITLE
works on `ubuntu-12.04`, fails on `14.04`

### ISSUE THREAD

**Issue by gretel** [poise/poise-monit#6]
running `chef-12.06` on `ubuntu-14.04`. happens with and without event queue. besides, it works perfectly fine on `12.04`. testing done using `test-kitchen` of both simultaenously.

```
           * monit_service[carbon-cache-d] action enable (up to date)
           * monit_service[carbon-cache-d] action start

       ================================================================================
             Error executing action `start` on resource 'monit_service[carbon-cache-d]'
             ================================================================================

             Mixlib::ShellOut::ShellCommandFailed
             ------------------------------------
             Expected process to exit with [0], but received '1'
             ---- Begin output of ["/usr/bin/monit", "-c", "/etc/monit/monitrc", "start", "carbon-cache-d"] ----

             STDERR: monit: action failed -- Other action already in progress -- please try again later
             ---- End output of ["/usr/bin/monit", "-c", "/etc/monit/monitrc", "start", "carbon-cache-d"] ----
       Ran ["/usr/bin/monit", "-c", "/etc/monit/monitrc", "start", "carbon-cache-d"] returned 1

             Cookbook Trace:
             ---------------
             /tmp/kitchen/cache/cookbooks/poise-monit/files/halite_gem/poise_monit/resources/monit_service.rb:176:in `monit_shell_out!'
             /tmp/kitchen/cache/cookbooks/poise-monit/files/halite_gem/poise_monit/resources/monit_service.rb:135:in `start_service'
             /tmp/kitchen/cache/cookbooks/poise-service/files/halite_gem/poise_service/service_providers/base.rb:74:in `block in action_start'
       /tmp/kitchen/cache/cookbooks/poise-service/files/halite_gem/poise_service/service_providers/base.rb:134:in `call'
             /tmp/kitchen/cache/cookbooks/poise-service/files/halite_gem/poise_service/service_providers/base.rb:134:in `notify_if_service'
       /tmp/kitchen/cache/cookbooks/poise-service/files/halite_gem/poise_service/service_providers/base.rb:73:in `action_start'
       /tmp/kitchen/cache/cookbooks/poise-service/files/halite_gem/poise_service/service_providers/base.rb:61:in `action_enable'

             Resource Declaration:
             ---------------------
             # In /tmp/kitchen/cache/cookbooks/xpl_graphite_ng/recipes/_carbon.rb

       135:   poise_service res_name do
       136:     command cmd
       137:     user node['graphite']['carbon']['user']
       138:     directory node['graphite']['base_path']

             140:     # templates.uniq.each do |t|
       141:     #   subscribes :restart, "template[#{t}]", :delayed
             142:     # end
             143:     # carbon daemons do not support signals, so KILL is the only thing we can do
       144:     stop_signal 'KILL'

             146:     options :monit, checks: "if failed host localhost port #{tcp_port} then alert", pid_file: pidfile
             147:     supports :restart => true, :reload => false, :status => true

             149:     retry_delay 3
       150:   end
             151:   # store hash of services to audit on later
             152:   instances << { 'daemon_name' => daemon_name, 'res_name' => res_name, 'instance' => instance, 'cmd' => cmd, 'config' => config }
             153: end
             154:

             Compiled Resource:
             ------------------
             # Declared in /tmp/kitchen/cache/cookbooks/xpl_graphite_ng/recipes/_carbon.rb:135:in `block in from_file'

       monit_service("carbon-cache-d") do
        action [:enable]
        supports {:restart=>nil, :reload=>nil, :status=>nil}
        retries 0
        retry_delay 2
        default_guard_interpreter :default
        service_name "carbon-cache-d"
        enabled true
         pattern "carbon-cache-d"
        init_command "/etc/init.d/carbon-cache-d"
        parent monit[monit]
        monit_config_path "/etc/monit/conf.d/carbon-cache-d.conf"
       end
```

**Comment by coderanger** [comment]
Does it work if you use the binaries provider to install a more recent monit?

**Comment by gretel** [comment]
while i have to use `:system` i did try - yes, it fails in the same way.

**Comment by coderanger** [comment]
Hrmm, so it sounds like Monit is being asked to run too many commands in close succession? There is code to automatically retry for 20 seconds. You can try (hackily) extending that from your recipe by adding `PoiseMonit::Resources::MonitService::DEFAULT_TIMEOUT = 60`. It will yell at you for redefining a const but it should allow it and that should let you try longer timeouts. If that ends up fixing it, I'll add that as a configurable option on `monit_service`.

**Comment by gretel** [comment]
the error message is quite famous and can have other reasons besides the obvious. today i had a single converge for ubuntu-14.04 which worked - next one failed again as described. the services managed are python scripts which ususally start and shutdown immediately. additionally, it's a aws c3.xlarge ssd-backed instance which is low on latencies overall.
i wonder if the restarts (or just reloads?) of monit itself can be a possible reason. could you possibly

```
set daemon  60              # check services at 1-minute intervals
    with start delay 5      # optional: delay the first check by 4-minutes (by
#                           # default Monit check immediately after Monit start)
```

**Comment by coderanger** [comment]
I avoided putting `set daemon` in the config in favor of `-d` on the command line so that you can still run it one-off from the command line to update things. The [loop in `monit_service`](https://github.com/poise/poise-monit/blob/master/lib/poise_monit/resources/monit_service.rb#L164-L189) retries on any failure so if waiting longer will fix it, that should catch it.

**Comment by gretel** [comment]
unfortunately, the `start delay` can not be set on the command line.
i don't feel like changing something i chef to compensate for not having a configuration statement in a component that should actually get managed by chef - not the other way around.

**Comment by coderanger** [comment]
You can add it yourself by providing your own template :)

``` ruby
monit 'monit' do
  provider :system
  config_source 'monit.conf.erb'
end
```

Or add it via a `monit_config`:

``` ruby
monit_config 'daemonize' do
  content 'SET DAEMON 60 WITH START DELAY 5'
end
```

**Comment by gretel** [comment]
so the latter one would replace the entry on `SET DAEMON` already present?

**Comment by coderanger** [comment]
There is no `SET DAEMON` in the default config, so it wouldn't replace it. There would still be a `-d` on the command line, not sure how that would interact.

**Comment by gretel** [comment]
ah sure that was what i meant, sorry. well it's ambigous at least.

**Comment by coderanger** [comment]
Better solution to this: I'll add the `start_delay` as a property to the `monit` resource. If that is set to false or 0, I use the current solution, if you want a start delay it puts it in the config instead of command line.

**Comment by coderanger** [comment]
Opinion, `daemon_delay`, `daemon_start_delay`, or `daemon_splay`?

**Comment by gretel** [comment]
`start_delay` in an `options` hash that would also take `verbose` for `-v` :)

**Comment by coderanger** [comment]
Good point on the verbose, how about if Chef is at log_level debug I make all commands verbose?

**Comment by coderanger** [comment]
(does running the monit service itself with `-v` do anything useful?)

**Comment by gretel** [comment]
as a default value `log_level` be fine but i'd love to have it at different levels. yeah it does dump lots more info could be useful for debugging, like you said, with chef at `debug`.

**Comment by gretel** [comment]
may i also suggest that `var_path` is bit misleading in comparison to the statement in the config file?

**Comment by coderanger** [comment]
What do you mean?

**Comment by gretel** [comment]
doh i am stupid. i was assuming it's been used to have the `statefile` set by `-s` there.

**Comment by coderanger** [comment]
It does, along with the ID file and event queue.

**Comment by gretel** [comment]
should get some sleep anyways :) it'd be nice to have both configurable too. on `EC2` all three can be put on a `EBS` volume so they do survive reboots on systems with ephemeral storage.

**Comment by coderanger** [comment]
My solution there was you can set `var_path false` and it disables that whole chunk of the config so you can write your own. https://github.com/poise/poise-monit/blob/master/chef/templates/monit.conf.erb#L9

I'll CC you on the pull request so you can review it in the morning.

**Comment by gretel** [comment]
thanks. btw, i'd love to have more than one `checks` line per service. sort of a feature request. shall i open issues accordingly?

**Comment by coderanger** [comment]
You mean for the `poise_service` provider?

**Comment by gretel** [comment]
yup, yes.

**Comment by coderanger** [comment]
You can pass an array for the `checks` option to have as many things as you want. https://github.com/poise/poise-monit/blob/master/chef/templates/monit_service.conf.erb#L4-L6

Does that cover it?

**Comment by gretel** [comment]
oops, sure, i did not notice. thanks.

**Comment by coderanger** [comment]
I should probably also allow straight up replacing the template too. Will add that to my mental todo list.

**Comment by gretel** [comment]
i also imagine something like a `monit_host` resource which would manage `check host` statements and configs. could be done with templates of course but i guess lots of people including me would like a `DSL`ish approach. personally, i use monits lots for host monitoring and other custom stuff.

**Comment by gretel** [comment]
so the `checks` option would also make me have statements like

```
check process whatever
  ...
  depends on another
  group ha
```

but then setting `depends` and `group` on the `checks` might be a bit misleading :)

**Comment by gretel** [comment]
```
# set up alias (virtual mapping)
ruby_block 'template-changed' do
  block do
    Chef::Log.warn("Configuration files changed!")
    node.set['audit']['config_changed'] = true
    # FIXME: hardcoded
    cmd = Mixlib::ShellOut.new("monit restart all")
    cmd.run_command
  end
  ignore_failure true
end
```

can you think of a more elegant way to achieve this?

**Comment by gretel** [comment]
@coderanger kindly pinging

**Comment by coderanger** [comment]
@gretel the `monit_config` resource does set its updated flag as you would expect, but Chef doesn't have anything to support sending a notification to all resources of a type. The correct-est way to do it would be to make a subresource of `monit` so it can find the right path to monit and use the right config file.
